# .github/workflows/deploy.yml
name: CI/CD Frontend

on:
  push:
    branches: [main]  # O "master" según el repositorio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Verificar archivos HTML, CSS, JS
        run: |
          echo "Listando archivos del proyecto..."
          ls -R

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Preparar carpeta de despliegue
        run: |
          mkdir deploy
          cp -r html/* deploy/
          cp -r css deploy/
          cp -r js deploy/
          cp -r img deploy/

      - name: Desplegar con GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

